### PR TITLE
build with cetmodules

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
code-checks

**Comment by gartung** [comment]
code-checks

**Comment by smuzaffar** [comment]
@gartung any idea why @FNALbuild tagged us here https://github.com/LArSoft/larvecutils/pull/1#issuecomment-1044838059 ?

**Comment by gartung** [comment]
The top level categories from cmssw/cms-bot somehow snuck in during a merge.

**Comment by gartung** [comment]
Or I left them in by mistake and cms-bot failed over to the top level categories.py because there wasn't a repo defined for larvecutils yet.

**Comment by lgarren** [comment]
approve

**Pull request merged**
